// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('../src/components/actions/Badge/Badge.stories')
  require('../src/components/actions/Button/Button.stories')
  require('../src/components/actions/HeaderActionButton/HeaderActionButton.stories')
  require('../src/components/actions/IconButton/IconButton.stories')
  require('../src/components/actions/Link/Link.stories')
  require('../src/components/actions/LinkButton/LinkButton.stories')
  require('../src/components/actions/Pill/Pill.stories')
  require('../src/components/feedback-indicators/Skeleton/Skeleton.stories')
  require('../src/components/feedback-indicators/SkeletonAvatar/SkeletonAvatar.stories')
  require('../src/components/feedback-indicators/SkeletonBodyText/SkeletonBodyText.stories')
  require('../src/components/feedback-indicators/SkeletonDisplayText/SkeletonDisplayText.stories')
  require('../src/components/feedback-indicators/SkeletonHeading/SkeletonHeading.stories')
  require('../src/components/feedback-indicators/SkeletonIcon/SkeletonIcon.stories')
  require('../src/components/feedback-indicators/SkeletonLoading/SkeletonLoading.stories')
  require('../src/components/feedback-indicators/Spinner/Spinner.stories')
  require('../src/components/forms/FormLayout/FormLayout.stories')
  require('../src/components/forms/InlineError/InlineError.stories')
  require('../src/components/forms/SearchField/SearchField.stories')
  require('../src/components/forms/Switch/Switch.stories')
  require('../src/components/forms/TextField/TextField.stories')
  require('../src/components/icons/Icon/Icon.stories')
  require('../src/components/screens/Explore.stories')
  require('../src/components/screens/Money.stories')
  require('../src/components/screens/Profile.stories')
  require('../src/components/structure/Box/Box.stories')
  require('../src/components/structure/ButtonGroup/ButtonGroup.stories')
  require('../src/components/structure/Card/Card.stories')
  require('../src/components/structure/Divider/Divider.stories')
  require('../src/components/structure/Layout/Layout.stories')
  require('../src/components/structure/Space/Space.stories')
  require('../src/components/structure/Stack/Stack.stories')
  require('../src/components/text/BodyText/BodyText.stories')
  require('../src/components/text/Caption/Caption.stories')
  require('../src/components/text/DisplayText/DisplayText.stories')
  require('../src/components/text/Heading/Heading.stories')
  require('../src/components/text/TextContainer/TextContainer.stories')
  require('../src/components/text/TextStyle/TextStyle.stories')
  require('../src/components/text/Typography.stories')
  require('../src/components/theme/Animation.stories')
  require('../src/components/theme/Borders.stories')
  require('../src/components/theme/Colors.stories')
  require('../src/components/theme/Dimensions.stories')
  require('../src/components/theme/Elevations.stories')
  require('../src/components/theme/Opacity.stories')
  require('../src/components/theme/Radius.stories')
}

const stories = [
  '../src/components/actions/Badge/Badge.stories',
  '../src/components/actions/Button/Button.stories',
  '../src/components/actions/HeaderActionButton/HeaderActionButton.stories',
  '../src/components/actions/IconButton/IconButton.stories',
  '../src/components/actions/Link/Link.stories',
  '../src/components/actions/LinkButton/LinkButton.stories',
  '../src/components/actions/Pill/Pill.stories',
  '../src/components/feedback-indicators/Skeleton/Skeleton.stories',
  '../src/components/feedback-indicators/SkeletonAvatar/SkeletonAvatar.stories',
  '../src/components/feedback-indicators/SkeletonBodyText/SkeletonBodyText.stories',
  '../src/components/feedback-indicators/SkeletonDisplayText/SkeletonDisplayText.stories',
  '../src/components/feedback-indicators/SkeletonHeading/SkeletonHeading.stories',
  '../src/components/feedback-indicators/SkeletonIcon/SkeletonIcon.stories',
  '../src/components/feedback-indicators/SkeletonLoading/SkeletonLoading.stories',
  '../src/components/feedback-indicators/Spinner/Spinner.stories',
  '../src/components/forms/FormLayout/FormLayout.stories',
  '../src/components/forms/InlineError/InlineError.stories',
  '../src/components/forms/SearchField/SearchField.stories',
  '../src/components/forms/Switch/Switch.stories',
  '../src/components/forms/TextField/TextField.stories',
  '../src/components/icons/Icon/Icon.stories',
  '../src/components/screens/Explore.stories',
  '../src/components/screens/Money.stories',
  '../src/components/screens/Profile.stories',
  '../src/components/structure/Box/Box.stories',
  '../src/components/structure/ButtonGroup/ButtonGroup.stories',
  '../src/components/structure/Card/Card.stories',
  '../src/components/structure/Divider/Divider.stories',
  '../src/components/structure/Layout/Layout.stories',
  '../src/components/structure/Space/Space.stories',
  '../src/components/structure/Stack/Stack.stories',
  '../src/components/text/BodyText/BodyText.stories',
  '../src/components/text/Caption/Caption.stories',
  '../src/components/text/DisplayText/DisplayText.stories',
  '../src/components/text/Heading/Heading.stories',
  '../src/components/text/TextContainer/TextContainer.stories',
  '../src/components/text/TextStyle/TextStyle.stories',
  '../src/components/text/Typography.stories',
  '../src/components/theme/Animation.stories',
  '../src/components/theme/Borders.stories',
  '../src/components/theme/Colors.stories',
  '../src/components/theme/Dimensions.stories',
  '../src/components/theme/Elevations.stories',
  '../src/components/theme/Opacity.stories',
  '../src/components/theme/Radius.stories',
]

module.exports = {
  loadStories,
  stories,
}
