name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the Repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history (for Chromatic)
      - name: Install node_modules
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Deploy to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: t00yilwkcv
          token: ${{ secrets.GITHUB_TOKEN }}
