name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the Repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history (for Chromatic)
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn modules cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node_modules
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Deploy to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: t00yilwkcv
          token: ${{ secrets.GITHUB_TOKEN }}
