# This workflow creates PRs from master to develop
name: Create master to develop Pull Request

on:
  push:
    branches:
      - master

jobs:
  create_pr:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2

      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: 'develop'
          pr_title: 'Merge master back into develop'
          pr_reviewer: 'alexbchr,hansgx'
          pr_body: 'Keep develop up-to-date with master'
