name: Merge master in develop

on:
  push:
    branches:
      - feature/release-workflow

jobs:
  merge:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history (for merging)
          ref: 'feature/release-workflow-dummy'

      - name: 'Pull master branch'
        run: |
          git pull origin feature/release-workflow --commit
          git push
