name: Build

on:
  pull_request:
    branches:
      - feature/release-workflow
    types:
      - closed

# On pushes to master branch, release package to NPM
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      # Step needed to extract release version from branch name
      #   - name: Extract Release Version
      #     id: extract_version
      #     run: echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/heads/release/})"

      - name: Print PR body
        run: echo "${{ toJson(github.event) }}"
#   - name: Create GitHub Release
#     id: create_release
#     uses: actions/create-release@v1
#     env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     with:
#       tag_name: ${{ github.ref }}
#       release_name: Release ${{ github.ref }}
#       body: |
#         Changes in this Release
#         - First Change
#         - Second Change
#       prerelease: false # TODO Set accordingly
